DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    try:
        from django.urls import re_path as url
    except ImportError:
        from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

HengDaProject/urls.py
from django.contrib import admin
from django.urls import include, path

from homeApp.views import home
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

admin.site.site_header = '恒达企业后台管理系统'
admin.site.site_title = '恒达企业管理'
admin.site.index_title = '欢迎使用企业管理系统'


urlpatterns = [
    path("admin/", admin.site.urls),
    path('',home,name='home'),
    path('aboutApp/',include('aboutApp.urls')),
    path('contactApp/',include('contactApp.urls')), # 人才招聘
    path('newsApp/',include('newsApp.urls')), # 新闻动态
    path('productsApp/',include('productsApp.urls')), # 产品中心
    path('scienceApp/',include('scienceApp.urls')),# 科研基地
    path('serviceApp/',include('serviceApp.urls')), # 服务支持
    path('ueditor/',include('DjangoUeditor.urls')),
    path('search/',include('haystack.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsApp/urls.py
from django.urls import path
from newsApp import views

app_name='newsApp'

urlpatterns = [
    path('news/<str:newName>/', views.news, name='news'),#新闻列表
    path('newDetail/<int:id>/', views.newDetail, name='newDetail'),
    path('search/', views.search, name='search'),
]

newsApp/models.py
from django.db import models
from DjangoUeditor.models import UEditorField
import django.utils.timezone as timezone

class MyNew(models.Model):
    NEWS_CHOICES=(
        ('企业要闻', '企业要闻'),
        ('行业新闻','行业新闻'),
        ('通知公告', '通知公告'),
    )

    photo = models.ImageField(upload_to='news/',
                            blank=True,
                            null=True,
                            verbose_name='展报')

    title = models.CharField(max_length=50, verbose_name='新闻标题')
    description =UEditorField(u'内容',default='',
                            width=1000,
                            height=300,
                            imagePath='news/images/',
                            filePath='news/files/',                     
                            )

    newType=models.CharField(max_length=50,choices=NEWS_CHOICES,verbose_name='新闻类型')
    publishDate=models.DateTimeField(default=timezone.now,verbose_name='发布时间',max_length=20)
    views=models.PositiveIntegerField('浏览量',default=0)

    def __str__(self):
        return self.title

    class Meta:
        ordering=['-publishDate']
        verbose_name='新闻'
        verbose_name_plural=verbose_name

newsApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import MyNew
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404
from pyquery import PyQuery as pq

def news(request,newName):
    submenu = newName
    if newName=='company':
        newName = '企业要闻'
    elif newName=='industry':
        newName = '行业新闻'
    else:
        newName='通知公告'

    newList = MyNew.objects.all().filter(newType=newName).order_by('-publishDate')

    for mynew in newList:
        html=pq(mynew.description)
        mynew.mytxt=pq(html)('p').text()
        
    # 分页
    p = Paginator(newList, 5)
    
    if p.num_pages<=1:
        pageData=''
    else:
        page=int(request.GET.get('page',1))
        newList=p.page(page)
        left=[]
        right=[]
        left_has_more=False
        right_has_more=False
        first=False
        last=False
        total_pages=p.num_pages
        page_range=p.page_range
        if page==1:
            right=page_range[page:page+2]
            print(total_pages)
            if right[-1]<total_pages-1:
                right_has_more=True
            if right[-1]<total_pages:
                last=True
        elif page==total_pages:
            left=page_range[(page-3)if(page-3)>0 else 0:page-1]
            if left[0]>2:
                left_has_more=True
            if left[0]>1: 
                first=True

        else:
            left=page_range[(page-3)if(page-3)>0 else 0:page-1]
            right=page_range[page:page+2]
            if left[0]>2:
                left_has_more=True
            if left[0]>1: 
                first=True
            if right[-1]<total_pages-1:
                right_has_more=True
            if right[-1]<total_pages:
                last=True

        pageData={
            'left':left,
            'right':right,
            'left_has_more':left_has_more,
            'right_has_more':right_has_more,
            'first':first,
            'last':last,
            'total_pages':total_pages,
            'page':page
        }
        
    return render(
        request,'newList.html',{
            'active_menu':'news',
            'sub_menu':submenu,
            'newName':newName,
            'newList': newList,
            'pageData':pageData,
        }
    )


def newDetail(request,id):
    mynew = get_object_or_404(MyNew,id=id)
    mynew.views += 1
    mynew.save()
    return render(
        request,'newDetail.html',{
            'active_menu':'news',
            'mynew':mynew
        }
    )

def search(request):
    keyword=request.GET.get('keyword')
    newList=MyNew.objects.filter(title__icontains=keyword)
    newName="关于"+"\""+keyword+"\""+"的搜索结果"
    return render(
        request,'searchList.html',{
            'active_menu':'news',
            'newName':newName,
            'newList': newList,
        }
    )

newsApp/templates/newDetail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
新闻详情
{% endblock %}
{% block content %}
<link href="{% static 'css/news.css' %}" rel="stylesheet">
{% comment %} 主体内容 {% endcomment %}
<div class="container">
    <div class="model-details-product-title">
        {{mynew.title}}
        <div class="model-foot">发布时间：{{mynew.publishDate|date:"Y-m-d"}}&nbsp;
            &nbsp;浏览次数:{{mynew.views}}</div>
        
    </div>
    <div class="model-details">
        {{mynew.description|safe}}
        
    </div>
</div>
{% endblock %}

newsApp/templates/newList.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{{newName}}
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/news.css' %}">
{% comment %}广告横幅  {% endcomment %}
<div class="container-fluid">
    <div class="row">
        <img class="img-responsive model-img" src={% static 'img/new1.jpg' %}>
    </div>
</div>
{% comment %} 主体内容 {% endcomment %}
<div class="container"> 
    <div class="row row-3">
        {% comment %} 侧边导航栏 {% endcomment %}
        <div class="col-md-3">
            <div class="model-title">
                新闻动态
            </div>
            <div class="model-list"> 
                <ul class="list-group">
                    <li class="list-group-item" id="company"> 
                        <a href="{% url 'newsApp:news' 'company' %}">企业要闻</a>
                    </li> 
                    <li class="list-group-item" id="industry"> 
                        <a href="{% url 'newsApp:news' 'industry' %}">行业新闻</a>
                    </li>
                    <li class="list-group-item" id="notice"> 
                        <a href="{% url 'newsApp:news' 'notice' %}">通知公告</a>
                    </li>
                </ul>
            </div>
        </div>
        {% comment %} 说明文字和图片 {% endcomment %}
        <div class="col-md-9"> 
            <div class="model-details-title">
                {{newName}}
                <div class="col-md-7 hidden-xs model-details-title-search">
                    <form method="get" id="searchform" action="{% url 'haystack_search' %}">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" name="q" class="form-control" placeholder="请输入关键词" required/>
                            <span class="input-group-btn">
                                <input type="submit" class="btn btn-primary" value="查询" />
                            </span>
                        </div>
                    </form>
                </div>
            </div>
            <div class="model-details">
                {% for mynew in newList %}
                    <div class="news-model">
                        <img src="{% static 'img/newsicon.png' %}">
                        <a href="{% url 'newsApp:newDetail' mynew.id %}"><b>{{mynew.title}}</b></a>
                        <span>【{{mynew.publishDate|date:"Y-m-d"}}】</span>
                        <p>
                            <!-- 添加新闻简要说明-->
                            {{mynew.mytxt|truncatechars:"110"}}...
                        </p>
                    </div>
                {% empty %}
                    <div class="alert alert-warning" style="margin-top: 15px;">
                        没有找到相关资料
                    </div>
                {% endfor %}

                {% if pageData %}
                <div class="paging">
                    <ul id="pages" class="pagination">
                        {% if pageData.first %}
                        <li>
                            <a href="?page=1">1</a>
                        </li>
                        {% endif %}
                        {% if pageData.left %}
                        {% if pageData.left_has_more %}
                        <li>
                            <span>...</span>
                        </li>
                        {% endif %}
                        {% for i in pageData.left %}
                        <li>
                            <a href="?page={{i}}">{{i}}</a>
                        </li>
                        {% endfor %}
                        {% endif %}
                        <li class="active">
                            <a href="?page={{pageData.page}}">{{pageData.page}}</a>
                        </li>
                        {% if pageData.right %}
                        {% for i in pageData.right %}
                        <li><a href="?page={{i}}">{{i}}</a></li>
                        {% endfor %}
                        {% if pageData.right_has_more %}
                        <li>
                            <span>...</span>
                        </li>
                        {% endif %}
                        {% endif %}
                        {% if pageData.last %}
                        <li>
                            <a href="?page={{pageData.total_pages}}">{{pageData.total_pages}}</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

newsApp/templates/searchList.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{{newName}}
{% endblock %}

{% block content %}
<link href="{% static 'css/news.css' %}" rel="stylesheet">
{% comment %} 广告横幅 {% endcomment %}
<div class="container-fluid">
    <div class="row">
        <img class="img-responsive model-img" src="{% static 'img/new1.jpg' %}">
    </div>
</div>
{% comment %} 主体内容 {% endcomment %}
<div class="container"> 
    <div class="row row-3">
        <div class="model-details-title">
            {{newName}}
            <div class="col-md-7 hidden-xs model-details-title-search">
                <form method="get" action="{% url 'newsApp:search' %}">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="text" class="form-control" name="keyword" placeholder="请输入关键词" required/>
                        <span class="input-group-btn">
                            <input type="submit" class="btn btn-default" value="查询" />
                        </span>
                    </div>
                </form>
            </div>
        </div>
        <div class="model-details">
            {% for mynew in newList %}
            <div class="news-model">
                <img src="{% static 'img/newsicon.png' %}">
                <a href="{% url 'newsApp:newDetail' mynew.id %}"><b>{{mynew.title}}</b></a>
                <span>【{{mynew.publishDate|date:"Y-m-d"}}】
                </span>
            </div>
            {% empty %}
                <div class="alert alert-warning" style="margin-top: 15px;">
                    没有找到相关资料
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}