DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    try:
        from django.urls import re_path as url
    except ImportError:
        from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

HengDaProject/urls.py
from django.contrib import admin
from django.urls import include, path

from homeApp.views import home
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

admin.site.site_header = '恒达企业后台管理系统'
admin.site.site_title = '恒达企业管理'
admin.site.index_title = '欢迎使用企业管理系统'


urlpatterns = [
    path("admin/", admin.site.urls),
    path('',home,name='home'),
    path('aboutApp/',include('aboutApp.urls')),
    path('contactApp/',include('contactApp.urls')), # 人才招聘
    path('newsApp/',include('newsApp.urls')), # 新闻动态
    path('productsApp/',include('productsApp.urls')), # 产品中心
    path('scienceApp/',include('scienceApp.urls')),# 科研基地
    path('serviceApp/',include('serviceApp.urls')), # 服务支持
    path('ueditor/',include('DjangoUeditor.urls')),
    path('search/',include('haystack.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

aboutApp/urls.py


from django.urls import path

from aboutApp import views


app_name='aboutApp' # 设置应用名

urlpatterns=[
    path('survey/',views.survey,name='survey'), # 添加企业概况二级路由
    path('honor/',views.honor,name='honor'),  # 添加企业荣誉二级路由
]

contactApp/urls.py
from django.urls import path
from contactApp import views


app_name='contactApp'  # 人才招聘

urlpatterns = [
    path('contact/', views.contact, name='contact'), # 欢迎咨询
    path('recruit/', views.recruit, name='recruit'),  # 加入恒达
    path('quick_feedback/', views.quick_feedback, name='quick_feedback'), # 留言
    path('query_feedback/', views.query_feedback, name='query_feedback') # 查询接口
]

newsApp/urls.py
from django.urls import path
from newsApp import views

app_name='newsApp'

urlpatterns = [
    path('news/<str:newName>/', views.news, name='news'),#新闻列表
    path('newDetail/<int:id>/', views.newDetail, name='newDetail'),
    path('search/', views.search, name='search'),
]

scienceApp/urls.py
from django.urls import path

from scienceApp import views

app_name ='scienceApp'

urlpatterns = [
    path('science/', views.science, name='science'), # 科研基地
]

serviceApp/urls.py
from django.urls import path

from serviceApp import views


app_name='serviceApp'

urlpatterns = [
    path('download/', views.download, name='download'), # 资料下载
    path('platform/', views.platform, name='platform'), # 人脸识别开放平台
    path('getDoc/<int:id>/',views.getDoc,name='getDoc'),
    path('facedetect/',views.facedetect,name='facedetect'), # 人脸检测api
    path('facedetectDemo/',views.facedetectDemo,name='facedetectDemo'),
    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>恒达科技| {% block title %}{% endblock  %} </title>
		<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
		<link rel="stylesheet" href="{% static 'css/style.css' %}" />
		<link rel="stylesheet" href="https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css">
		<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		
	</head>
	<body>
		<div class="container top">
			<div class="row">
				<!-- 图片 - 占6列（保持原宽度） -->
				<div class="col-md-6">
					<a>
						<img class="img-responsive" src="{% static 'img/mingzi.jpg' %}" />
					</a>
				</div>
				
				<!-- 三条信息各占2列 -->
				<div class="col-md-2 hidden-xs">
					<div style="padding: 5px;">
						<div style="display: flex; align-items: center;">
							<span class="glyphicon glyphicon-phone" style="min-width: 20px;"></span>
							<span>电话：400 1111 0000</span>
						</div>
					</div>
				</div>
				
				<div class="col-md-2 hidden-xs custom-width" style="width: 23% !important;">
					<div style="padding: 5px;">
						<div style="display: flex; align-items: center;">
							<span class="glyphicon glyphicon-envelope" style="min-width: 20px;"></span>
							<span >邮箱：hengda@126.com</span>
						</div>
					</div>
				</div>
				
				<div class="col-md-2 hidden-xs" style="width:18%">
					<div style="padding: 5px;">
						<div style="display: flex; align-items: center;">
							<a href="\admin\login" class="staff-link">
								<span class="glyphicon glyphicon-user" style="min-width: 20px;"></span>
								<span>员工通道</span>
							</a>							
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- 导航栏 -->
		<nav class="navbar navbar-default" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button
						type="button"
						class="navbar-toggle collapsed"
						data-toggle="collapse"
						data-target="#bs-example"
						aria-expanded="false"
					>
						<span>导航栏</span>
					</button>
				</div>
				<div class="collapse navbar-collapse" id="bs-example">
					<ul class="nav navbar-nav" style="width: 100%;">
						<li class="nav-top" id='home'>
							<a href="{% url 'home' %}">首页</a>
						</li>
						<li class="dropdown nav-top {% if active_menu == 'about' %}active{% endif %} " id='about' >
							<a href="#" class="dropdown-toggle on" data-toggle="dropdown"
								>公司简介</a
							>
							<ul class="dropdown-menu">
								<li><a href="{% url 'aboutApp:survey' %}">企业概况</a></li>
								<li><a href="{% url 'aboutApp:honor' %}">荣誉资质</a></li>
							</ul>
						</li>
						<li class="dropdown nav-top {% if active_menu == 'news' %}active{% endif %}" id='news'>
							<a href="#" class="dropdown-toggle on" data-toggle="dropdown"
								>新闻动态</a
							>
							<ul class="dropdown-menu">
								<li><a href="{% url 'newsApp:news' 'company' %}">企业要闻</a></li>
								<li><a href="{% url 'newsApp:news' 'industry' %}">行业新闻</a></li>
								<li><a href="{% url 'newsApp:news' 'notice'%}">通知公告</a></li>
							</ul>
						</li>
						<li class="dropdown nav-top {% if active_menu == 'products' %}active{% endif %}" id='products'>
							<a href="#" class="dropdown-toggle on" data-toggle="dropdown"
								>产品中心</a
							>
							<ul class="dropdown-menu">
								<li>
									<a href="{% url 'productsApp:products' 'robot' %}">家用机器人</a>
								</li>
								<li>
									<a href="{% url 'productsApp:products' 'monitor' %}">智能监控</a>
								</li>
								<li>
									<a href="{% url 'productsApp:products' 'face' %}">人脸识别解决方案</a>
								</li>
							</ul>
						</li>
						<li class="dropdown nav-top {% if active_menu == 'service' %}active{% endif %}">
							<a href="#" class="dropdown-toggle on" data-toggle="dropdown"
								>服务支持</a
							>
							<ul class="dropdown-menu">
								<li>
									<a href="{% url 'serviceApp:download' %}">资料下载</a>
								</li>
								<li>
									<a href="{% url 'serviceApp:platform' %}">人脸识别开放平台</a>
								</li>
							</ul>
						</li>
						<li class="nav-top " id='science'>
							<a href="{% url 'scienceApp:science' %}">科研基地</a>
						</li>
						<li class="dropdown nav-top  {% if active_menu == 'contactus' %}active{% endif %}">
							<a href="#" class="dropdown-toggle on" data-toggle="dropdown"
								>人才招聘</a
							>
							<ul class="dropdown-menu">
								<li><a href="{% url 'contactApp:contact' %}">欢迎咨询</a></li>
								<li><a href="{% url 'contactApp:recruit' %}">加入恒达</a></li>
							</ul>
						</li>
											
					</ul>
				</div>
			</div>
			
		</nav>
		<div class="line"></div>
		{% block content %}{% endblock  %}
		{% comment %} 设置站点地图 {% endcomment %}
		<div class="container web-footer">
			<div class="row" id="map-footer">
				<div class="col-md-2">
					<dl>
						<dt>公司简介</dt>
						<dd><a href="{% url 'aboutApp:survey' %}">企业概况</a></dd>
						<dd><a href="{% url 'aboutApp:honor' %}">荣誉资质</a></dd>
					</dl>
				</div>
				<div class="col-md-2"> 
					<dl>
						<dt>产品中心</dt>
						<dd><a href="{% url 'productsApp:products' 'robot' %}">家用机器人</a></dd>
						<dd><a href="{% url 'productsApp:products' 'monitor'%}">智能监控</a></dd>
						<dd><a href="{% url 'productsApp:products' 'face'%}">人脸识别解决方案</a></dd>
					</dl>
				</div>
				<div class="col-md-2"> 
					<dl>
						<dt>服务支持</dt>
						<dd><a href="{% url 'serviceApp:download' %}">资料下载</a></dd>
						<dd><a href="{% url 'serviceApp:platform' %}">人脸识别开放平台</a></dd>
					</dl>
					</dl>
				</div>
				<div class="col-md-2"> 
					<dl>
						<dt>人才招牌</dt>
						<dd><a href="{% url 'contactApp:contact' %}">欢迎咨询</a></dd>
						<dd><a href="{% url 'contactApp:recruit' %}">加入恒达</a></dd>
					</dl>
				</div>
				<div class="col-md-4" id="wx"> 
					<p>
						扫描二维码，关注我们

					</p>
					<img class="qrimg" src="{% static 'img/qr_with_logo.png' %}" alt="wx" />
					<p>客服热线：<b style="font-size:20px">400 111 2222</b></p>
				</div>
			</div>
			{% comment %} 版权 {% endcomment %}
			<div class="row" id="patent-footer">
				<p>&copy 2019 Python Web 企业门户 版权所有 | 苏 ICP 备 19006378 号</p>
			</div>

			{% comment %} 悬浮窗 {% endcomment %}
			<div id="feedback-launcher">
				<i class="fa fa-comments-o"></i>
			</div>
			
			<div id="feedback-window">
				<div class="feedback-header">
					<span id="feedback-title" style="font-style: normal;">快速留言反馈</span>
					<button type="button" id="close-feedback">&times;</button>
				</div>

				<div id="submit-panel">
					<form id="feedback-form">
						{% csrf_token %}
						<div class="form-group">
							<input type="text" name="name" class="form-control" placeholder="您的姓名" required>
						</div>
						<div class="form-group" style="position: relative;">
							<input type="text" id="fb-phone" name="phone" class="form-control" placeholder="联系电话" required>
							<small id="phone-error-msg" style="color: #ff4d4f; display: none; font-size: 12px; margin-top: 5px;">
								<i class="fa fa-exclamation-circle"></i> 请输入正确的11位手机号
							</small>
						</div>
						<div class="form-group" style="position: relative;">
							<textarea id="fb-message" name="message" class="form-control" rows="3" placeholder="写下您的需求..." maxlength="200" required></textarea>
							<div id="char-count" style="text-align: right; font-size: 12px; color: #999; margin-top: 5px;">
								<span id="current-chars">0</span> / 200 字
							</div>
						</div>
						<button type="submit" id="fb-submit-btn" class="btn btn-primary btn-block" style="border-radius: 20px;">立即发送</button>
					</form>
					<div style="text-align: center; margin-top: 10px;">
						<a href="javascript:void(0);" id="switch-to-query" style="font-size: 12px; color: #666;">已有留言？点击查询进度</a>
					</div>
				</div>

				<div id="query-panel" style="display: none;">
					<div class="form-group">
						<input type="text" id="query-phone" class="form-control" placeholder="请输入提交时的手机号">
					</div>
					<button type="button" id="do-query" class="btn btn-info btn-block" style="border-radius: 20px;">立即查询</button>
					
					<div id="query-result" style="margin-top: 15px; font-size: 13px; max-height: 200px; overflow-y: auto; display: none;">
						</div>
			
					<div style="text-align: center; margin-top: 10px;">
						<a href="javascript:void(0);" id="switch-to-submit" style="font-size: 12px; color: #666;">返回在线留言</a>
					</div>
				</div>

			</div>
		</div>

		<script>
			$(function () {
				$(".dropdown").mouseover(function () {
					$(this).addClass("open");
				});
				$(".dropdown").mouseleave(function () {
					$(this).removeClass("open");
				});
			});
		</script>
        <script type='text/javascript'>
            $('#{{active_menu}}').addClass('active');
        </script>
		<script type="text/javascript">
			$('#{{sub_menu}}').addClass("active");
		</script>
		
		<script type="text/javascript">
			$(document).ready(function() {
				// --- 界面切换逻辑 ---
				// 切换到查询面板
				$('#switch-to-query').click(function() {
					$('#submit-panel').hide();
					$('#query-panel').fadeIn();
					$('#feedback-title').text('留言进度查询');
				});

				// 切换回提交面板
				$('#switch-to-submit').click(function() {
					$('#query-panel').hide();
					$('#submit-panel').fadeIn();
					$('#feedback-title').text('快速留言反馈');
				});

				// --- 执行查询逻辑 ---
				$('#do-query').click(function() {
					var phone = $('#query-phone').val();
					if(!phone) { alert("请输入手机号"); return; }
			
					$.ajax({
						url: "{% url 'contactApp:query_feedback' %}", // 需在urls.py配置此路由
						type: "GET",
						data: { 'phone': phone },
						success: function(data) {
							var resDiv = $('#query-result');
							resDiv.empty().show();
							
							if (data.status === 'success' && data.list.length > 0) {
								data.list.forEach(function(item) {
									var statusBtn = item.status === 'completed' ? 'label-success' : 'label-warning';
									var statusText = item.status === 'completed' ? '已回复' : '处理中';
									
									var html = '<div style="border-bottom: 1px dashed #eee; padding: 8px 0;">' +
											'<div><span class="label ' + statusBtn + '">' + statusText + '</span> <small class="text-muted">' + item.time + '</small></div>' +
											'<div style="margin-top:5px;"><b>问：</b>' + item.message + '</div>';
									if(item.reply) {
										html += '<div style="color: #005197; margin-top:3px;"><b>答：</b>' + item.reply + '</div>';
									}
									html += '</div>';
									resDiv.append(html);
								});
							} else {
								resDiv.append('<div class="text-center text-danger">未找到相关留言记录</div>');
							}
						},
						error: function() { alert("查询失败，请检查网络"); }
					});
				});

				const $phoneInput = $('#fb-phone');
				const $messageInput = $('#fb-message');
				const $submitBtn = $('#fb-submit-btn');
				const $phoneError = $('#phone-error-msg');
				const $charCountText = $('#current-chars');

				// 状态管理
				let isPhoneValid = false;
				let isMessageValid = false;

				// 1. 手机号正则验证 (中国大陆 11 位手机号)
				$phoneInput.on('input propertychange', function() {
					const val = $(this).val();
					const phoneReg = /^1[3-9]\d{9}$/; // 验证1开头，第二位3-9的11位数字
			
					if (val.length === 0) {
						$phoneError.hide();
						$(this).removeClass('input-error');
						isPhoneValid = false;
					} else if (!phoneReg.test(val)) {
						$phoneError.show();
						$(this).addClass('input-error').removeClass('input-success');
						isPhoneValid = false;
					} else {
						$phoneError.hide();
						$(this).removeClass('input-error').addClass('input-success');
						isPhoneValid = true;
					}
					validateForm();
				});

				// 2. 留言字数实时统计
				$messageInput.on('input propertychange', function() {
					const len = $(this).val().length;
					$charCountText.text(len);
					
					// 临界值视觉提示
					if (len >= 190) {
						$charCountText.parent().css('color', '#ff4d4f');
					} else {
						$charCountText.parent().css('color', '#999');
					}
			
					isMessageValid = len > 0 && len <= 200;
					validateForm();
				});

				// 3. 表单提交按钮状态控制
				function validateForm() {
					// 只有手机号格式正确且留言不为空时，才启用发送按钮
					if (isPhoneValid && isMessageValid) {
						$submitBtn.prop('disabled', false);
					} else {
						$submitBtn.prop('disabled', true);
					}
				}
			
				

				// 1. 点击圆球弹出/收起
				$('#feedback-launcher').on('click', function(e) {
					$('#feedback-window').stop().fadeToggle(300);
					e.stopPropagation(); // 阻止事件冒泡
				});
		
				// 2. 点击叉号关闭
				$('#close-feedback').on('click', function() {
					$('#feedback-window').fadeOut(300);
				});
		
				// 3. 点击弹窗内部不关闭
				$('#feedback-window').on('click', function(e) {
					e.stopPropagation();
				});
		
				// 4. 点击页面其他地方自动关闭
				$(document).on('click', function() {
					$('#feedback-window').fadeOut(300);
				});

				// 初始化时先禁用按钮
				validateForm();
			});
			$('#feedback-form').submit(function(e) {
				e.preventDefault();
				$.ajax({
					url: "{% url 'contactApp:quick_feedback' %}",
					type: "POST",
					data: $(this).serialize(),
					success: function(data) {
						if (data.status === 'success') {
							alert("提交成功！您可以切换到查询界面查看进度。");
							$('#feedback-form')[0].reset();
						} else {
							alert("错误：" + data.msg);
						}
					}
				});
			});
		</script>
	</body>
</html>